device: "cpu"
batch_size: 64
checkpoint: "best_model_10.pt"

model:
    _target_: models.svdresnet.scripts.model.SVDResNet
    num_classes: 10
    patch_size: 8
    compression_ratio: 1
    u_output_dim: 96
    vt_output_dim: 24

val_loader:
    _target_: torch.utils.data.DataLoader
    dataset: ${val_set_tiny}
    batch_size: ${batch_size} 
    shuffle: true
    

### Other
val_transform_tiny:
    _target_: torchvision.transforms.Compose
    transforms:
        - _target_: torchvision.transforms.Normalize
          mean: [0.5, 0.5, 0.5]
          std: [0.5, 0.5, 0.5]
        - _target_: torchvision.transforms.ToTensor

val_transform:
    _target_: torchvision.transforms.Compose
    transforms:
        - _target_: torchvision.transforms.Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
        - _target_: torchvision.transforms.ToTensor

val_set_tiny:
    _target_: torchvision.datasets.ImageFolder
    root: ./datasets/tiny_imagenet_200/test
    transform: ${val_transform_tiny}

val_set:
    _target_: torchvision.datasets.CIFAR10
    root: "./datasets"
    transform: ${val_transform}
    train: false
    download: True

loss:
    _target_: torch.nn.CrossEntropyLoss

val_metrics:
    top_1_accuracy:
        _target_: ignite.metrics.TopKCategoricalAccuracy
        k: 1
    top_5_accuracy:
        _target_: ignite.metrics.TopKCategoricalAccuracy
        k: 5
    loss:
        _target_: ignite.metrics.Loss
        loss_fn: ${loss}
