######### metric #########

######### handler #########
# checkpoint
checkpoint:
    dirname: checkpoints
    n_saved: 2
    filename_prefix: best
    score_name: "accuracy"

# TensorBoard logger
log_interval: 100
