_target_: src.models.DCTModel
net:
    _target_: src.models.resnet50
    _partial_: true
num_classes: 10
original_size: 32
domain: compressed
new_size:
    _target_: numpy.arange
    start: 8
    stop: 33
    step: 1
pad: false
no_grad: true
