_target_: src.models.DCTModel
net:
    _target_: torchvision.models.resnet50
    _partial_: true
num_classes: 1000
original_size: 224
domain: compressed
new_size:
    _target_: numpy.arange
    start: 32
    stop: 225
    step: 1
pad: false
zscore: false
no_grad: true
