_target_: src.models.InterpolateModel
net:
    _target_: src.models.resnet50
    _partial_: true
num_classes: 10
rescale: false
original_size: 32
new_size:
    _target_: numpy.arange
    start: 2
    stop: 33
    step: 1
no_grad: true
