_target_: src.models.InterpolateModel
net:
    _target_: torchvision.models.resnet50
    _partial_: true
num_classes: 200
rescale: false
original_size: 64
new_size:
    _target_: numpy.arange
    start: 12
    stop: 65
    step: 1
no_grad: true
