_target_: src.models.InterpolateModel
net:
    _target_: torchvision.models.resnet50
    _partial_: true
num_classes: 1000
rescale: false
original_size: 224
new_size:
    _target_: numpy.arange
    start: 2
    stop: 225
    step: 1
no_grad: true
