_target_: src.models.PatchSVDModel
net:
    _target_: torchvision.models.resnet50
    _partial_: true
num_classes: 1000
patch_size: 8
domain: decompressed
rank:
    _target_: numpy.arange
    start: 1
    stop: 192
    step: 1
no_grad: true
