defaults:
    - _self_
    - data: cifar10
    - model: resnet
    - handler: [progressbar, model_checkpoint]
    - logger: [pylogger, tensorboard]
    - trainer: trainer
    - metric: imagenet

task_name: "train"
seed: 42
logger_output_path: "./outputs/logger/"
