defaults:
    - _self_
    - data: tinyimagenet
    - model: resnet
    - handler: [checkpoint, common]
    - logger: [pylogger, tensorboard]
    - trainer: trainer
    - metric: imagenet

task_name: "train"
seed: 42
