defaults:
    - _self_
    - path: default
    - hydra: default
    - data: cifar10
    - model: resnet
    - handler: [progressbar, checkpoint]
    - logger: [pylogger, tensorboard]
    - trainer: trainer
    - metric: cifar10

task_name: "train"
seed: 42
distributed:
    backend: null
    nproc_per_node: null
    nnodes: null
