defaults:
    - _self_
    - path: default
    - hydra: default
    - data: cifar10
    - model: resnet50_model_cifar
    - handler: [checkpoint, pylogger, tensorboard]
    - trainer: default
    - metric: cifar

task_name: train
seed: 42

dist:
    backend: null
    nproc_per_node: null
    nnodes: null
