defaults:
    - _self_
    - path: default
    - hydra: default
    - data: cifar10
    - model: resnet
    - handler: [checkpoint]
    - logger: [pylogger, tensorboard]
    - trainer: trainer
    - metric: cifar10

task_name: "train"
seed: 42

distributed:
    backend: nccl
    nproc_per_node: 2
    nnodes: 1
