defaults:
    - _self_
    - data: cifar10
    - model: resnet
    - handler: null
    - logger: [tensorboard]
    - trainer: trainer
    - metric: imagenet

task_name: "train"
seed: 42
logger_output_path: "./outputs/logger/"

checkpoint:
    dirname: ./outputs/checkpoints
    n_saved: 2
    filename_prefix: best
    score_name: "accuracy"
