defaults:
    - _self_
    - path: default
    - hydra: default
    - data: cifar10
    - model: dct_model_cifar
    - handler: [checkpoint, pylogger, tensorboard]
    - trainer: trainer
    - metric: cifar10

task_name: train
seed: 42

dist:
    backend: null
    nproc_per_node: null
    nnodes: null
